const blogs = [
    {
      id: 1,
      title: "Web Automation Testing using Selenium",
      author: "John Doe",
      publicationDate: new Date("2023-01-15T12:30:00Z"),
      imageUrl: "https://www.perfecto.io/sites/default/files/styles/social_preview_image/public/image/2020-09/social-blog-what-to-expect-with-selenium-2.jpg?itok=E-wILp8w",
      excerpt: "In this blog, we explore the world of web automation testing using Selenium.",
      likes: 25,
      comments: 10,
    },
    {
      id: 2,
      title: "Getting Started with React Hooks",
      author: "Jane Smith",
      publicationDate: new Date("2023-02-10T09:45:00Z"),
      imageUrl: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20210714205336/Things-You-Should-Know-About-React-Hooks.png",
      excerpt: "Learn the basics of React Hooks and how they simplify state management in React applications.",
      likes: 30,
      comments: 15,
    },
    {
      id: 3,
      title: "Node.js Best Practices",
      author: "Alex Johnson",
      publicationDate: new Date("2023-03-05T15:20:00Z"),
      imageUrl: "https://miro.medium.com/v2/resize:fit:950/1*WCV6lR1xIJNkNvrSBwDT7Q.jpeg",
      excerpt: "Discover the best practices for developing robust and scalable applications with Node.js.",
      likes: 40,
      comments: 20,
    },
    {
      id: 4,
      title: "Deep Learning Fundamentals",
      author: "Emily White",
      publicationDate: new Date("2023-04-20T14:10:00Z"),
      imageUrl: "https://contentstatic.techgig.com/photo/89608359/fundamental-concepts-of-ai-machine-learning-and-deep-learning.jpg?4862485",
      excerpt: "Delve into the fundamental concepts of deep learning and its applications in AI.",
      likes: 15,
      comments: 8,
    },
    {
      id: 5,
      title: "Mastering CSS Grid Layout",
      author: "Chris Brown",
      publicationDate: new Date("2023-05-12T11:55:00Z"),
      imageUrl: "https://www.freecodecamp.org/news/content/images/2022/05/CSS-GRID-3.png",
      excerpt: "A comprehensive guide to mastering the CSS Grid Layout for modern web design.",
      likes: 35,
      comments: 18,
    },
    {
      id: 6,
      title: "GraphQL: A Powerful API Query Language",
      author: "Sarah Miller",
      publicationDate: new Date("2023-06-08T08:30:00Z"),
      imageUrl: "https://kinsta.com/wp-content/uploads/2022/09/graphql.png",
      excerpt: "Explore the benefits and capabilities of GraphQL as a powerful API query language.",
      likes: 28,
      comments: 12,
    },
    {
      id: 7,
      title: "Python for Data Science: A Practical Guide",
      author: "Michael Turner",
      publicationDate: new Date("2023-07-03T16:45:00Z"),
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX-Y3HF-D_QgGIm-LSltWPrOrSmD1wwV3obA&usqp=CAU",
      excerpt: "Learn Python for data science with hands-on examples and practical tips.",
      likes: 22,
      comments: 14,
    },
    {
      id: 8,
      title: "Responsive Web Design Strategies",
      author: "Emma Davis",
      publicationDate: new Date("2023-08-18T13:20:00Z"),
      imageUrl: "https://cdn-gcp.new.marutitech.com/medium_Responsive_Web_Design_Key_Element_of_Web_Strategy_e0ad5b269d.jpg",
      excerpt: "Implement effective strategies for creating responsive web designs that adapt to various devices.",
      likes: 32,
      comments: 16,
    },
  ];
  
  export default blogs;
  